#!/bin/bash
#PBS -N dock-a-rama
#PBS -j oe
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00:00
#PBS -q dept_24_core

echo Running on `hostname`
echo workdir $PBS_O_WORKDIR
echo ld_library_path $LD_LIBRARY_PATH

#for some reason when the job starts on the node, it auto-cd's to your home dir
cd $PBS_O_WORKDIR

#compute_row.py < -n "${PBS_ARRAYID}p" > PDB.distances

cmd=`sed -n "${PBS_ARRAYID}p" jobs`
echo $cmd
$cmd




exit

