babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1avp/1avp_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1avp1avp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1bxl/1bxl_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1bxl1bxl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1d3v/1d3v_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1d3v1d3v_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1d4w/1d4w_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1d4w1d4w_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1eoj/1eoj_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1eoj1eoj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1eol/1eol_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1eol1eol_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1esz/1esz_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1esz1esz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1ewj/1ewj_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1ewj1ewj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1f3j/1f3j_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1f3j1f3j_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1f47/1f47_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1f471f47_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1fhr/1fhr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1fhr1fhr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1g1e/1g1e_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1g1e1g1e_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1g42/1g42_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1g421g42_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1gag/1gag_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1gag1gag_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1guw/1guw_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1guw1guw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1h07/1h07_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1h071h07_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1h24/1h24_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1h241h24_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1h28/1h28_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1h281h28_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1h2u/1h2u_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1h2u1h2u_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1haa/1haa_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1haa1haa_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1hq5/1hq5_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1hq51hq5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1hyz/1hyz_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1hyz1hyz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1i3z/1i3z_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1i3z1i3z_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1i5h/1i5h_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1i5h1i5h_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1i8h/1i8h_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1i8h1i8h_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1idg/1idg_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1idg1idg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1iht/1iht_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1iht1iht_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1ilq/1ilq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1ilq1ilq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1iwq/1iwq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1iwq1iwq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1j19/1j19_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1j191j19_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1j4k/1j4k_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1j4k1j4k_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1j4p/1j4p_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1j4p1j4p_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1j4q/1j4q_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1j4q1j4q_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1j7z/1j7z_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1j7z1j7z_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1j80/1j80_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1j801j80_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1j81/1j81_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1j811j81_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1jif/1jif_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1jif1jif_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1jm4/1jm4_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1jm41jm4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1jyc/1jyc_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1jyc1jyc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1k2v/1k2v_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1k2v1k2v_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1k3n/1k3n_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1k3n1k3n_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1ka7/1ka7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1ka71ka7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1kf6/1kf6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1kf61kf6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1klg/1klg_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1klg1klg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1l0a/1l0a_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1l0a1l0a_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1lcj/1lcj_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1lcj1lcj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1lvk/1lvk_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1lvk1lvk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1lxh/1lxh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1lxh1lxh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1mpa/1mpa_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1mpa1mpa_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1mxl/1mxl_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1mxl1mxl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1n4m/1n4m_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1n4m1n4m_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1n7m/1n7m_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1n7m1n7m_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1o9k/1o9k_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1o9k1o9k_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1oeb/1oeb_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1oeb1oeb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1oh4/1oh4_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1oh41oh4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1oj5/1oj5_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1oj51oj5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1onp/1onp_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1onp1onp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1opi/1opi_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1opi1opi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1oqp/1oqp_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1oqp1oqp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1ow6/1ow6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1ow61ow6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1ow7/1ow7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1ow71ow7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1ow8/1ow8_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1ow81ow8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1pq3/1pq3_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1pq31pq3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1qwf/1qwf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1qwf1qwf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1r2b/1r2b_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1r2b1r2b_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1r5w/1r5w_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1r5w1r5w_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1s5q/1s5q_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1s5q1s5q_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1sje/1sje_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1sje1sje_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1t08/1t08_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1t081t08_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1t29/1t29_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1t291t29_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1t2v/1t2v_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1t2v1t2v_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1thr/1thr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1thr1thr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1tka/1tka_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1tka1tka_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1tkc/1tkc_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1tkc1tkc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1uti/1uti_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1uti1uti_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1vyj/1vyj_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1vyj1vyj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1w4l/1w4l_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1w4l1w4l_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1w6r/1w6r_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1w6r1w6r_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1w76/1w76_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1w761w76_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1wva/1wva_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1wva1wva_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1xh3/1xh3_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1xh31xh3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1xhm/1xhm_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1xhm1xhm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1xn3/1xn3_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1xn31xn3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1xot/1xot_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1xot1xot_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1xp0/1xp0_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1xp01xp0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1ywh/1ywh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1ywh1ywh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1zhk/1zhk_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1zhk1zhk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/1zhl/1zhl_lig.smi /home/dkoes/PDBbind/general-set-without-refined//1zhl1zhl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2a4w/2a4w_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2a4w2a4w_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2auc/2auc_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2auc2auc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2df6/2df6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2df62df6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2eep/2eep_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2eep2eep_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2emt/2emt_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2emt2emt_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2flu/2flu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2flu2flu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2fm0/2fm0_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2fm02fm0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2fuu/2fuu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2fuu2fuu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2fx7/2fx7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2fx72fx7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2fx8/2fx8_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2fx82fx8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2fx9/2fx9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2fx92fx9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2gph/2gph_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2gph2gph_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2h2d/2h2d_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2h2d2h2d_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2hug/2hug_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2hug2hug_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2ivz/2ivz_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2ivz2ivz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2jb6/2jb6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2jb62jb6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2jld/2jld_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2jld2jld_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2jq9/2jq9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2jq92jq9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2k00/2k00_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2k002k00_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2k7l/2k7l_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2k7l2k7l_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2kbr/2kbr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2kbr2kbr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2kfg/2kfg_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2kfg2kfg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2kfh/2kfh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2kfh2kfh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2knh/2knh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2knh2knh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2koh/2koh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2koh2koh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2kpl/2kpl_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2kpl2kpl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2krd/2krd_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2krd2krd_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2ks9/2ks9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2ks92ks9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2ksa/2ksa_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2ksa2ksa_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2ksb/2ksb_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2ksb2ksb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2ksp/2ksp_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2ksp2ksp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2kup/2kup_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2kup2kup_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2kvm/2kvm_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2kvm2kvm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2kwn/2kwn_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2kwn2kwn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2kzu/2kzu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2kzu2kzu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2l11/2l11_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2l112l11_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2l12/2l12_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2l122l12_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2l1b/2l1b_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2l1b2l1b_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2l6e/2l6e_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2l6e2l6e_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2l7u/2l7u_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2l7u2l7u_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2l8j/2l8j_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2l8j2l8j_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2lbm/2lbm_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2lbm2lbm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2lcs/2lcs_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2lcs2lcs_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2lct/2lct_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2lct2lct_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2lgf/2lgf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2lgf2lgf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2ll6/2ll6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2ll62ll6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2ll7/2ll7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2ll72ll7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2llo/2llo_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2llo2llo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2llq/2llq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2llq2llq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2lo6/2lo6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2lo62lo6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2lsk/2lsk_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2lsk2lsk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2lsp/2lsp_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2lsp2lsp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2lto/2lto_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2lto2lto_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2lyw/2lyw_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2lyw2lyw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2m0o/2m0o_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2m0o2m0o_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2m41/2m41_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2m412m41_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2mg5/2mg5_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2mg52mg5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2mkr/2mkr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2mkr2mkr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2mow/2mow_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2mow2mow_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2mpa/2mpa_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2mpa2mpa_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2mpm/2mpm_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2mpm2mpm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2mps/2mps_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2mps2mps_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2mwo/2mwo_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2mwo2mwo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2mwp/2mwp_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2mwp2mwp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2nm1/2nm1_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2nm12nm1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2p3o/2p3o_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2p3o2p3o_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2p8o/2p8o_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2p8o2p8o_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2peh/2peh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2peh2peh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2pl9/2pl9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2pl92pl9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2pll/2pll_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2pll2pll_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2pv2/2pv2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2pv22pv2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2q2y/2q2y_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2q2y2q2y_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2q2z/2q2z_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2q2z2q2z_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2qhr/2qhr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2qhr2qhr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2qqs/2qqs_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2qqs2qqs_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2rnw/2rnw_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2rnw2rnw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2rnx/2rnx_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2rnx2rnx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2rny/2rny_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2rny2rny_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2rqu/2rqu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2rqu2rqu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2v85/2v85_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2v852v85_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2v86/2v86_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2v862v86_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2v87/2v87_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2v872v87_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2vwf/2vwf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2vwf2vwf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2w16/2w16_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2w162w16_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2w6t/2w6t_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2w6t2w6t_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2w6u/2w6u_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2w6u2w6u_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2w73/2w73_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2w732w73_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2w76/2w76_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2w762w76_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2w77/2w77_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2w772w77_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2w78/2w78_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2w782w78_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2wfg/2wfg_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2wfg2wfg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2x6w/2x6w_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2x6w2x6w_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2xxn/2xxn_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2xxn2xxn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2y4m/2y4m_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2y4m2y4m_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2y6s/2y6s_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2y6s2y6s_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2y9q/2y9q_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2y9q2y9q_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2ycf/2ycf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2ycf2ycf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2yir/2yir_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2yir2yir_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2yns/2yns_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2yns2yns_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2yq6/2yq6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2yq62yq6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2z3z/2z3z_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2z3z2z3z_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/2z5s/2z5s_lig.smi /home/dkoes/PDBbind/general-set-without-refined//2z5s2z5s_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3agm/3agm_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3agm3agm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3anq/3anq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3anq3anq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3aqa/3aqa_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3aqa3aqa_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3are/3are_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3are3are_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3arf/3arf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3arf3arf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3arg/3arg_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3arg3arg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3bhb/3bhb_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3bhb3bhb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3bho/3bho_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3bho3bho_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3bim/3bim_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3bim3bim_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3bki/3bki_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3bki3bki_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3bl2/3bl2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3bl23bl2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3btr/3btr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3btr3btr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3bu6/3bu6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3bu63bu6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3bu8/3bu8_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3bu83bu8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3buo/3buo_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3buo3buo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3bwf/3bwf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3bwf3bwf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3c3o/3c3o_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3c3o3c3o_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3c3q/3c3q_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3c3q3c3q_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3cfs/3cfs_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3cfs3cfs_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3cfv/3cfv_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3cfv3cfv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3cst/3cst_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3cst3cst_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3ctr/3ctr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3ctr3ctr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3d45/3d45_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3d453d45_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3dcs/3dcs_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3dcs3dcs_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3e0p/3e0p_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3e0p3e0p_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3e6k/3e6k_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3e6k3e6k_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3e6v/3e6v_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3e6v3e6v_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3e9b/3e9b_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3e9b3e9b_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3eht/3eht_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3eht3eht_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3eqy/3eqy_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3eqy3eqy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3eu7/3eu7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3eu73eu7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3evf/3evf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3evf3evf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3exf/3exf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3exf3exf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3eyd/3eyd_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3eyd3eyd_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3f9n/3f9n_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3f9n3f9n_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3f9y/3f9y_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3f9y3f9y_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3fdm/3fdm_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3fdm3fdm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3fe7/3fe7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3fe73fe7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3fea/3fea_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3fea3fea_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3fxz/3fxz_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3fxz3fxz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3fy0/3fy0_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3fy03fy0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3ggw/3ggw_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3ggw3ggw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3gxz/3gxz_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3gxz3gxz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3h1z/3h1z_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3h1z3h1z_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3h52/3h52_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3h523h52_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3hhu/3hhu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3hhu3hhu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3hnb/3hnb_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3hnb3hnb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3hxi/3hxi_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3hxi3hxi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3i91/3i91_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3i913i91_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3iaf/3iaf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3iaf3iaf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3ij1/3ij1_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3ij13ij1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3ilq/3ilq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3ilq3ilq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3isw/3isw_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3isw3isw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3iwy/3iwy_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3iwy3iwy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3jzo/3jzo_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3jzo3jzo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3jzp/3jzp_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3jzp3jzp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3jzq/3jzq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3jzq3jzq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3jzr/3jzr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3jzr3jzr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3jzs/3jzs_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3jzs3jzs_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3k27/3k27_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3k273k27_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3kl8/3kl8_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3kl83kl8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3ktr/3ktr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3ktr3ktr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3l3q/3l3q_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3l3q3l3q_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3l3z/3l3z_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3l3z3l3z_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3l6f/3l6f_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3l6f3l6f_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3l6x/3l6x_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3l6x3l6x_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3lkj/3lkj_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3lkj3lkj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3lq4/3lq4_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3lq43lq4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3lrh/3lrh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3lrh3lrh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3m59/3m59_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3m593m59_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3m5a/3m5a_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3m5a3m5a_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3m93/3m93_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3m933m93_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3m94/3m94_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3m943m94_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3mmr/3mmr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3mmr3mmr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3mo8/3mo8_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3mo83mo8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3mpe/3mpe_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3mpe3mpe_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3o0e/3o0e_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3o0e3o0e_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3o6l/3o6l_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3o6l3o6l_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3oap/3oap_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3oap3oap_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3ob1/3ob1_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3ob13ob1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3ob2/3ob2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3ob23ob2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3oe6/3oe6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3oe63oe6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3oe8/3oe8_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3oe83oe8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3oe9/3oe9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3oe93oe9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3pdh/3pdh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3pdh3pdh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3plu/3plu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3plu3plu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3q4c/3q4c_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3q4c3q4c_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3q6s/3q6s_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3q6s3q6s_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3q8h/3q8h_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3q8h3q8h_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3qio/3qio_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3qio3qio_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3qlb/3qlb_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3qlb3qlb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3qo2/3qo2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3qo23qo2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3r93/3r93_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3r933r93_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3rbm/3rbm_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3rbm3rbm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3rj7/3rj7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3rj73rj7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3rq7/3rq7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3rq73rq7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3rz9/3rz9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3rz93rz9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3shj/3shj_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3shj3shj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3sjt/3sjt_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3sjt3sjt_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3skk/3skk_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3skk3skk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3so6/3so6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3so63so6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3src/3src_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3src3src_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3t0w/3t0w_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3t0w3t0w_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3tdu/3tdu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3tdu3tdu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3tiw/3tiw_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3tiw3tiw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3tpx/3tpx_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3tpx3tpx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3u2q/3u2q_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3u2q3u2q_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3u4h/3u4h_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3u4h3u4h_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3u4i/3u4i_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3u4i3u4i_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3u6j/3u6j_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3u6j3u6j_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3uat/3uat_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3uat3uat_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3ui2/3ui2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3ui23ui2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3upy/3upy_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3upy3upy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3uvu/3uvu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3uvu3uvu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3uxg/3uxg_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3uxg3uxg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3v30/3v30_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3v303v30_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3v31/3v31_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3v313v31_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3v4j/3v4j_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3v4j3v4j_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3vjs/3vjs_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3vjs3vjs_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3vjt/3vjt_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3vjt3vjt_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3w69/3w69_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3w693w69_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wax/3wax_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wax3wax_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wcb/3wcb_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wcb3wcb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wcf/3wcf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wcf3wcf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wcg/3wcg_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wcg3wcg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wch/3wch_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wch3wch_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wci/3wci_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wci3wci_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wcl/3wcl_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wcl3wcl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3whw/3whw_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3whw3whw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wp0/3wp0_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wp03wp0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wp1/3wp1_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wp13wp1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3wuu/3wuu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3wuu3wuu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3zha/3zha_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3zha3zha_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3zjt/3zjt_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3zjt3zjt_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3zju/3zju_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3zju3zju_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3zjv/3zjv_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3zjv3zjv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3zkf/3zkf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3zkf3zkf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3zp9/3zp9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3zp93zp9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3zqi/3zqi_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3zqi3zqi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/3zyr/3zyr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//3zyr3zyr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4a1w/4a1w_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4a1w4a1w_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4a2a/4a2a_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4a2a4a2a_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4acu/4acu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4acu4acu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4aom/4aom_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4aom4aom_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4aza/4aza_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4aza4aza_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4b6u/4b6u_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4b6u4b6u_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4b8o/4b8o_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4b8o4b8o_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4bea/4bea_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4bea4bea_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4bpi/4bpi_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4bpi4bpi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4bpj/4bpj_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4bpj4bpj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4bxu/4bxu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4bxu4bxu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4cpu/4cpu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4cpu4cpu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4cy1/4cy1_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4cy14cy1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4dcx/4dcx_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4dcx4dcx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4dcy/4dcy_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4dcy4dcy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4djs/4djs_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4djs4djs_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4dma/4dma_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4dma4dma_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4dow/4dow_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4dow4dow_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4dt6/4dt6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4dt64dt6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4e5f/4e5f_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4e5f4e5f_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ejf/4ejf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ejf4ejf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4erq/4erq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4erq4erq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4euc/4euc_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4euc4euc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4fea/4fea_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4fea4fea_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4fgy/4fgy_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4fgy4fgy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4fi9/4fi9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4fi94fi9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4fil/4fil_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4fil4fil_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ft2/4ft2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ft24ft2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4fyh/4fyh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4fyh4fyh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4g8l/4g8l_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4g8l4g8l_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ga3/4ga3_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ga34ga3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ge6/4ge6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ge64ge6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4gk2/4gk2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4gk24gk2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4gk3/4gk3_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4gk34gk3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4gk4/4gk4_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4gk44gk4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4gq6/4gq6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4gq64gq6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4h3q/4h3q_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4h3q4h3q_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4hmq/4hmq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4hmq4hmq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4hs6/4hs6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4hs64hs6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4hww/4hww_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4hww4hww_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4hxq/4hxq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4hxq4hxq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4hze/4hze_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4hze4hze_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4i06/4i06_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4i064i06_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4i60/4i60_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4i604i60_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4i7c/4i7c_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4i7c4i7c_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ie2/4ie2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ie24ie2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ie3/4ie3_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ie34ie3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ii9/4ii9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ii94ii9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4is6/4is6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4is64is6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4iu0/4iu0_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4iu04iu0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4iu4/4iu4_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4iu44iu4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ixu/4ixu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ixu4ixu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ixv/4ixv_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ixv4ixv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4j24/4j24_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4j244j24_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4j26/4j26_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4j264j26_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4j8s/4j8s_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4j8s4j8s_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4jmh/4jmh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4jmh4jmh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4k6t/4k6t_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4k6t4k6t_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4k6u/4k6u_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4k6u4k6u_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4k6v/4k6v_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4k6v4k6v_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4k6w/4k6w_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4k6w4k6w_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4kai/4kai_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4kai4kai_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4kb7/4kb7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4kb74kb7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4kbi/4kbi_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4kbi4kbi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4kii/4kii_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4kii4kii_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4l6q/4l6q_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4l6q4l6q_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4lg6/4lg6_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4lg64lg6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4lng/4lng_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4lng4lng_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4lv1/4lv1_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4lv14lv1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4m7c/4m7c_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4m7c4m7c_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4mmf/4mmf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4mmf4mmf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4mnw/4mnw_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4mnw4mnw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4mnx/4mnx_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4mnx4mnx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4mzj/4mzj_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4mzj4mzj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4mzk/4mzk_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4mzk4mzk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4mzl/4mzl_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4mzl4mzl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4n1z/4n1z_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4n1z4n1z_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4nb3/4nb3_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4nb34nb3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ngh/4ngh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ngh4ngh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4nhc/4nhc_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4nhc4nhc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4nmq/4nmq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4nmq4nmq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4no1/4no1_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4no14no1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4nuf/4nuf_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4nuf4nuf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4o36/4o36_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4o364o36_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4o37/4o37_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4o374o37_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ob0/4ob0_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ob04ob0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ob1/4ob1_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ob14ob1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ob2/4ob2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ob24ob2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ofb/4ofb_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ofb4ofb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4oru/4oru_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4oru4oru_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4orx/4orx_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4orx4orx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ory/4ory_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ory4ory_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ov5/4ov5_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ov54ov5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4oyk/4oyk_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4oyk4oyk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4oys/4oys_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4oys4oys_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4pz5/4pz5_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4pz54pz5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4q3q/4q3q_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4q3q4q3q_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4q3r/4q3r_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4q3r4q3r_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4q3s/4q3s_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4q3s4q3s_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4qbm/4qbm_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4qbm4qbm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4qjr/4qjr_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4qjr4qjr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4qk4/4qk4_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4qk44qk4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4qqi/4qqi_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4qqi4qqi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4qy8/4qy8_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4qy84qy8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4r1e/4r1e_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4r1e4r1e_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4ris/4ris_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4ris4ris_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4rlp/4rlp_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4rlp4rlp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4rme/4rme_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4rme4rme_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4tzm/4tzm_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4tzm4tzm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4tzq/4tzq_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4tzq4tzq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4u0x/4u0x_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4u0x4u0x_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4u5t/4u5t_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4u5t4u5t_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4um9/4um9_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4um94um9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4utn/4utn_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4utn4utn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4uwg/4uwg_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4uwg4uwg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4uwk/4uwk_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4uwk4uwk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4whh/4whh_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4whh4whh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4wkt/4wkt_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4wkt4wkt_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4wku/4wku_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4wku4wku_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4wkv/4wkv_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4wkv4wkv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4wy7/4wy7_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4wy74wy7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4x34/4x34_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4x344x34_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4x7k/4x7k_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4x7k4x7k_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4x9r/4x9r_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4x9r4x9r_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4x9v/4x9v_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4x9v4x9v_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4x9w/4x9w_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4x9w4x9w_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4xgz/4xgz_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4xgz4xgz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4xh2/4xh2_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4xh24xh2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4xkc/4xkc_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4xkc4xkc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4xqa/4xqa_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4xqa4xqa_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4xqb/4xqb_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4xqb4xqb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4y16/4y16_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4y164y16_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4yyn/4yyn_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4yyn4yyn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4z8a/4z8a_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4z8a4z8a_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/4zdu/4zdu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//4zdu4zdu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5aer/5aer_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5aer5aer_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5afx/5afx_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5afx5afx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5agi/5agi_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5agi5agi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5agj/5agj_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5agj5agj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5ahu/5ahu_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5ahu5ahu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5ajo/5ajo_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5ajo5ajo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5ajp/5ajp_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5ajp5ajp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5ddd/5ddd_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5ddd5ddd_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5dde/5dde_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5dde5dde_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5e4w/5e4w_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5e4w5e4w_lig.sdf
babel --gen3D /home/dkoes/PDBbind/general-set-without-refined/5eay/5eay_lig.smi /home/dkoes/PDBbind/general-set-without-refined//5eay5eay_lig.sdf
