babel --gen3D /home/dkoes/PDBbind/1av_lig.smi /home/dkoes/PDBbind/1av_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1bx_lig.smi /home/dkoes/PDBbind/1bx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1d3_lig.smi /home/dkoes/PDBbind/1d3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1d4_lig.smi /home/dkoes/PDBbind/1d4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1eo_lig.smi /home/dkoes/PDBbind/1eo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1eo_lig.smi /home/dkoes/PDBbind/1eo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1es_lig.smi /home/dkoes/PDBbind/1es_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ew_lig.smi /home/dkoes/PDBbind/1ew_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1f3_lig.smi /home/dkoes/PDBbind/1f3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1f4_lig.smi /home/dkoes/PDBbind/1f4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1fh_lig.smi /home/dkoes/PDBbind/1fh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1g1_lig.smi /home/dkoes/PDBbind/1g1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1g4_lig.smi /home/dkoes/PDBbind/1g4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ga_lig.smi /home/dkoes/PDBbind/1ga_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1gu_lig.smi /home/dkoes/PDBbind/1gu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1h0_lig.smi /home/dkoes/PDBbind/1h0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1h2_lig.smi /home/dkoes/PDBbind/1h2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1h2_lig.smi /home/dkoes/PDBbind/1h2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1h2_lig.smi /home/dkoes/PDBbind/1h2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ha_lig.smi /home/dkoes/PDBbind/1ha_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1hq_lig.smi /home/dkoes/PDBbind/1hq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1hy_lig.smi /home/dkoes/PDBbind/1hy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1i3_lig.smi /home/dkoes/PDBbind/1i3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1i5_lig.smi /home/dkoes/PDBbind/1i5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1i8_lig.smi /home/dkoes/PDBbind/1i8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1id_lig.smi /home/dkoes/PDBbind/1id_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ih_lig.smi /home/dkoes/PDBbind/1ih_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1il_lig.smi /home/dkoes/PDBbind/1il_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1iw_lig.smi /home/dkoes/PDBbind/1iw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1j1_lig.smi /home/dkoes/PDBbind/1j1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1j4_lig.smi /home/dkoes/PDBbind/1j4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1j4_lig.smi /home/dkoes/PDBbind/1j4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1j4_lig.smi /home/dkoes/PDBbind/1j4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1j7_lig.smi /home/dkoes/PDBbind/1j7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1j8_lig.smi /home/dkoes/PDBbind/1j8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1j8_lig.smi /home/dkoes/PDBbind/1j8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ji_lig.smi /home/dkoes/PDBbind/1ji_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1jm_lig.smi /home/dkoes/PDBbind/1jm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1jy_lig.smi /home/dkoes/PDBbind/1jy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1k2_lig.smi /home/dkoes/PDBbind/1k2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1k3_lig.smi /home/dkoes/PDBbind/1k3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ka_lig.smi /home/dkoes/PDBbind/1ka_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1kf_lig.smi /home/dkoes/PDBbind/1kf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1kl_lig.smi /home/dkoes/PDBbind/1kl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1l0_lig.smi /home/dkoes/PDBbind/1l0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1lc_lig.smi /home/dkoes/PDBbind/1lc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1lv_lig.smi /home/dkoes/PDBbind/1lv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1lx_lig.smi /home/dkoes/PDBbind/1lx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1mp_lig.smi /home/dkoes/PDBbind/1mp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1mx_lig.smi /home/dkoes/PDBbind/1mx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1n4_lig.smi /home/dkoes/PDBbind/1n4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1n7_lig.smi /home/dkoes/PDBbind/1n7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1o9_lig.smi /home/dkoes/PDBbind/1o9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1oe_lig.smi /home/dkoes/PDBbind/1oe_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1oh_lig.smi /home/dkoes/PDBbind/1oh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1oj_lig.smi /home/dkoes/PDBbind/1oj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1on_lig.smi /home/dkoes/PDBbind/1on_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1op_lig.smi /home/dkoes/PDBbind/1op_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1oq_lig.smi /home/dkoes/PDBbind/1oq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ow_lig.smi /home/dkoes/PDBbind/1ow_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ow_lig.smi /home/dkoes/PDBbind/1ow_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ow_lig.smi /home/dkoes/PDBbind/1ow_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1pq_lig.smi /home/dkoes/PDBbind/1pq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1qw_lig.smi /home/dkoes/PDBbind/1qw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1r2_lig.smi /home/dkoes/PDBbind/1r2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1r5_lig.smi /home/dkoes/PDBbind/1r5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1s5_lig.smi /home/dkoes/PDBbind/1s5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1sj_lig.smi /home/dkoes/PDBbind/1sj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1t0_lig.smi /home/dkoes/PDBbind/1t0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1t2_lig.smi /home/dkoes/PDBbind/1t2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1t2_lig.smi /home/dkoes/PDBbind/1t2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1th_lig.smi /home/dkoes/PDBbind/1th_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1tk_lig.smi /home/dkoes/PDBbind/1tk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1tk_lig.smi /home/dkoes/PDBbind/1tk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1ut_lig.smi /home/dkoes/PDBbind/1ut_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1vy_lig.smi /home/dkoes/PDBbind/1vy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1w4_lig.smi /home/dkoes/PDBbind/1w4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1w6_lig.smi /home/dkoes/PDBbind/1w6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1w7_lig.smi /home/dkoes/PDBbind/1w7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1wv_lig.smi /home/dkoes/PDBbind/1wv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1xh_lig.smi /home/dkoes/PDBbind/1xh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1xh_lig.smi /home/dkoes/PDBbind/1xh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1xn_lig.smi /home/dkoes/PDBbind/1xn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1xo_lig.smi /home/dkoes/PDBbind/1xo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1xp_lig.smi /home/dkoes/PDBbind/1xp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1yw_lig.smi /home/dkoes/PDBbind/1yw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1zh_lig.smi /home/dkoes/PDBbind/1zh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/1zh_lig.smi /home/dkoes/PDBbind/1zh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2a4_lig.smi /home/dkoes/PDBbind/2a4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2au_lig.smi /home/dkoes/PDBbind/2au_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2df_lig.smi /home/dkoes/PDBbind/2df_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ee_lig.smi /home/dkoes/PDBbind/2ee_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2em_lig.smi /home/dkoes/PDBbind/2em_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2fl_lig.smi /home/dkoes/PDBbind/2fl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2fm_lig.smi /home/dkoes/PDBbind/2fm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2fu_lig.smi /home/dkoes/PDBbind/2fu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2fx_lig.smi /home/dkoes/PDBbind/2fx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2fx_lig.smi /home/dkoes/PDBbind/2fx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2fx_lig.smi /home/dkoes/PDBbind/2fx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2gp_lig.smi /home/dkoes/PDBbind/2gp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2h2_lig.smi /home/dkoes/PDBbind/2h2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2hu_lig.smi /home/dkoes/PDBbind/2hu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2iv_lig.smi /home/dkoes/PDBbind/2iv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2jb_lig.smi /home/dkoes/PDBbind/2jb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2jl_lig.smi /home/dkoes/PDBbind/2jl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2jq_lig.smi /home/dkoes/PDBbind/2jq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2k0_lig.smi /home/dkoes/PDBbind/2k0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2k7_lig.smi /home/dkoes/PDBbind/2k7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2kb_lig.smi /home/dkoes/PDBbind/2kb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2kf_lig.smi /home/dkoes/PDBbind/2kf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2kf_lig.smi /home/dkoes/PDBbind/2kf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2kn_lig.smi /home/dkoes/PDBbind/2kn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ko_lig.smi /home/dkoes/PDBbind/2ko_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2kp_lig.smi /home/dkoes/PDBbind/2kp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2kr_lig.smi /home/dkoes/PDBbind/2kr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ks_lig.smi /home/dkoes/PDBbind/2ks_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ks_lig.smi /home/dkoes/PDBbind/2ks_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ks_lig.smi /home/dkoes/PDBbind/2ks_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ks_lig.smi /home/dkoes/PDBbind/2ks_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ku_lig.smi /home/dkoes/PDBbind/2ku_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2kv_lig.smi /home/dkoes/PDBbind/2kv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2kw_lig.smi /home/dkoes/PDBbind/2kw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2kz_lig.smi /home/dkoes/PDBbind/2kz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2l1_lig.smi /home/dkoes/PDBbind/2l1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2l1_lig.smi /home/dkoes/PDBbind/2l1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2l1_lig.smi /home/dkoes/PDBbind/2l1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2l6_lig.smi /home/dkoes/PDBbind/2l6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2l7_lig.smi /home/dkoes/PDBbind/2l7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2l8_lig.smi /home/dkoes/PDBbind/2l8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2lb_lig.smi /home/dkoes/PDBbind/2lb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2lc_lig.smi /home/dkoes/PDBbind/2lc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2lc_lig.smi /home/dkoes/PDBbind/2lc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2lg_lig.smi /home/dkoes/PDBbind/2lg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ll_lig.smi /home/dkoes/PDBbind/2ll_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ll_lig.smi /home/dkoes/PDBbind/2ll_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ll_lig.smi /home/dkoes/PDBbind/2ll_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ll_lig.smi /home/dkoes/PDBbind/2ll_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2lo_lig.smi /home/dkoes/PDBbind/2lo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ls_lig.smi /home/dkoes/PDBbind/2ls_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ls_lig.smi /home/dkoes/PDBbind/2ls_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2lt_lig.smi /home/dkoes/PDBbind/2lt_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2ly_lig.smi /home/dkoes/PDBbind/2ly_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2m0_lig.smi /home/dkoes/PDBbind/2m0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2m4_lig.smi /home/dkoes/PDBbind/2m4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2mg_lig.smi /home/dkoes/PDBbind/2mg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2mk_lig.smi /home/dkoes/PDBbind/2mk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2mo_lig.smi /home/dkoes/PDBbind/2mo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2mp_lig.smi /home/dkoes/PDBbind/2mp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2mp_lig.smi /home/dkoes/PDBbind/2mp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2mp_lig.smi /home/dkoes/PDBbind/2mp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2mw_lig.smi /home/dkoes/PDBbind/2mw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2mw_lig.smi /home/dkoes/PDBbind/2mw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2nm_lig.smi /home/dkoes/PDBbind/2nm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2p3_lig.smi /home/dkoes/PDBbind/2p3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2p8_lig.smi /home/dkoes/PDBbind/2p8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2pe_lig.smi /home/dkoes/PDBbind/2pe_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2pl_lig.smi /home/dkoes/PDBbind/2pl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2pl_lig.smi /home/dkoes/PDBbind/2pl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2pv_lig.smi /home/dkoes/PDBbind/2pv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2q2_lig.smi /home/dkoes/PDBbind/2q2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2q2_lig.smi /home/dkoes/PDBbind/2q2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2qh_lig.smi /home/dkoes/PDBbind/2qh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2qq_lig.smi /home/dkoes/PDBbind/2qq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2rn_lig.smi /home/dkoes/PDBbind/2rn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2rn_lig.smi /home/dkoes/PDBbind/2rn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2rn_lig.smi /home/dkoes/PDBbind/2rn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2rq_lig.smi /home/dkoes/PDBbind/2rq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2v8_lig.smi /home/dkoes/PDBbind/2v8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2v8_lig.smi /home/dkoes/PDBbind/2v8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2v8_lig.smi /home/dkoes/PDBbind/2v8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2vw_lig.smi /home/dkoes/PDBbind/2vw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2w1_lig.smi /home/dkoes/PDBbind/2w1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2w6_lig.smi /home/dkoes/PDBbind/2w6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2w6_lig.smi /home/dkoes/PDBbind/2w6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2w7_lig.smi /home/dkoes/PDBbind/2w7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2w7_lig.smi /home/dkoes/PDBbind/2w7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2w7_lig.smi /home/dkoes/PDBbind/2w7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2w7_lig.smi /home/dkoes/PDBbind/2w7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2wf_lig.smi /home/dkoes/PDBbind/2wf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2x6_lig.smi /home/dkoes/PDBbind/2x6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2xx_lig.smi /home/dkoes/PDBbind/2xx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2y4_lig.smi /home/dkoes/PDBbind/2y4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2y6_lig.smi /home/dkoes/PDBbind/2y6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2y9_lig.smi /home/dkoes/PDBbind/2y9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2yc_lig.smi /home/dkoes/PDBbind/2yc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2yi_lig.smi /home/dkoes/PDBbind/2yi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2yn_lig.smi /home/dkoes/PDBbind/2yn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2yq_lig.smi /home/dkoes/PDBbind/2yq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2z3_lig.smi /home/dkoes/PDBbind/2z3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/2z5_lig.smi /home/dkoes/PDBbind/2z5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ag_lig.smi /home/dkoes/PDBbind/3ag_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3an_lig.smi /home/dkoes/PDBbind/3an_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3aq_lig.smi /home/dkoes/PDBbind/3aq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ar_lig.smi /home/dkoes/PDBbind/3ar_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ar_lig.smi /home/dkoes/PDBbind/3ar_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ar_lig.smi /home/dkoes/PDBbind/3ar_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bh_lig.smi /home/dkoes/PDBbind/3bh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bh_lig.smi /home/dkoes/PDBbind/3bh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bi_lig.smi /home/dkoes/PDBbind/3bi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bk_lig.smi /home/dkoes/PDBbind/3bk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bl_lig.smi /home/dkoes/PDBbind/3bl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bt_lig.smi /home/dkoes/PDBbind/3bt_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bu_lig.smi /home/dkoes/PDBbind/3bu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bu_lig.smi /home/dkoes/PDBbind/3bu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bu_lig.smi /home/dkoes/PDBbind/3bu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3bw_lig.smi /home/dkoes/PDBbind/3bw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3c3_lig.smi /home/dkoes/PDBbind/3c3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3c3_lig.smi /home/dkoes/PDBbind/3c3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3cf_lig.smi /home/dkoes/PDBbind/3cf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3cf_lig.smi /home/dkoes/PDBbind/3cf_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3cs_lig.smi /home/dkoes/PDBbind/3cs_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ct_lig.smi /home/dkoes/PDBbind/3ct_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3d4_lig.smi /home/dkoes/PDBbind/3d4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3dc_lig.smi /home/dkoes/PDBbind/3dc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3e0_lig.smi /home/dkoes/PDBbind/3e0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3e6_lig.smi /home/dkoes/PDBbind/3e6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3e6_lig.smi /home/dkoes/PDBbind/3e6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3e9_lig.smi /home/dkoes/PDBbind/3e9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3eh_lig.smi /home/dkoes/PDBbind/3eh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3eq_lig.smi /home/dkoes/PDBbind/3eq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3eu_lig.smi /home/dkoes/PDBbind/3eu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ev_lig.smi /home/dkoes/PDBbind/3ev_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ex_lig.smi /home/dkoes/PDBbind/3ex_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ey_lig.smi /home/dkoes/PDBbind/3ey_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3f9_lig.smi /home/dkoes/PDBbind/3f9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3f9_lig.smi /home/dkoes/PDBbind/3f9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3fd_lig.smi /home/dkoes/PDBbind/3fd_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3fe_lig.smi /home/dkoes/PDBbind/3fe_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3fe_lig.smi /home/dkoes/PDBbind/3fe_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3fx_lig.smi /home/dkoes/PDBbind/3fx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3fy_lig.smi /home/dkoes/PDBbind/3fy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3gg_lig.smi /home/dkoes/PDBbind/3gg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3gx_lig.smi /home/dkoes/PDBbind/3gx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3h1_lig.smi /home/dkoes/PDBbind/3h1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3h5_lig.smi /home/dkoes/PDBbind/3h5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3hh_lig.smi /home/dkoes/PDBbind/3hh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3hn_lig.smi /home/dkoes/PDBbind/3hn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3hx_lig.smi /home/dkoes/PDBbind/3hx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3i9_lig.smi /home/dkoes/PDBbind/3i9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ia_lig.smi /home/dkoes/PDBbind/3ia_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ij_lig.smi /home/dkoes/PDBbind/3ij_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3il_lig.smi /home/dkoes/PDBbind/3il_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3is_lig.smi /home/dkoes/PDBbind/3is_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3iw_lig.smi /home/dkoes/PDBbind/3iw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3jz_lig.smi /home/dkoes/PDBbind/3jz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3jz_lig.smi /home/dkoes/PDBbind/3jz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3jz_lig.smi /home/dkoes/PDBbind/3jz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3jz_lig.smi /home/dkoes/PDBbind/3jz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3jz_lig.smi /home/dkoes/PDBbind/3jz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3k2_lig.smi /home/dkoes/PDBbind/3k2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3kl_lig.smi /home/dkoes/PDBbind/3kl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3kt_lig.smi /home/dkoes/PDBbind/3kt_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3l3_lig.smi /home/dkoes/PDBbind/3l3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3l3_lig.smi /home/dkoes/PDBbind/3l3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3l6_lig.smi /home/dkoes/PDBbind/3l6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3l6_lig.smi /home/dkoes/PDBbind/3l6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3lk_lig.smi /home/dkoes/PDBbind/3lk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3lq_lig.smi /home/dkoes/PDBbind/3lq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3lr_lig.smi /home/dkoes/PDBbind/3lr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3m5_lig.smi /home/dkoes/PDBbind/3m5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3m5_lig.smi /home/dkoes/PDBbind/3m5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3m9_lig.smi /home/dkoes/PDBbind/3m9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3m9_lig.smi /home/dkoes/PDBbind/3m9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3mm_lig.smi /home/dkoes/PDBbind/3mm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3mo_lig.smi /home/dkoes/PDBbind/3mo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3mp_lig.smi /home/dkoes/PDBbind/3mp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3o0_lig.smi /home/dkoes/PDBbind/3o0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3o6_lig.smi /home/dkoes/PDBbind/3o6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3oa_lig.smi /home/dkoes/PDBbind/3oa_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ob_lig.smi /home/dkoes/PDBbind/3ob_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ob_lig.smi /home/dkoes/PDBbind/3ob_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3oe_lig.smi /home/dkoes/PDBbind/3oe_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3oe_lig.smi /home/dkoes/PDBbind/3oe_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3oe_lig.smi /home/dkoes/PDBbind/3oe_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3pd_lig.smi /home/dkoes/PDBbind/3pd_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3pl_lig.smi /home/dkoes/PDBbind/3pl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3q4_lig.smi /home/dkoes/PDBbind/3q4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3q6_lig.smi /home/dkoes/PDBbind/3q6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3q8_lig.smi /home/dkoes/PDBbind/3q8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3qi_lig.smi /home/dkoes/PDBbind/3qi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ql_lig.smi /home/dkoes/PDBbind/3ql_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3qo_lig.smi /home/dkoes/PDBbind/3qo_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3r9_lig.smi /home/dkoes/PDBbind/3r9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3rb_lig.smi /home/dkoes/PDBbind/3rb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3rj_lig.smi /home/dkoes/PDBbind/3rj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3rq_lig.smi /home/dkoes/PDBbind/3rq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3rz_lig.smi /home/dkoes/PDBbind/3rz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3sh_lig.smi /home/dkoes/PDBbind/3sh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3sj_lig.smi /home/dkoes/PDBbind/3sj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3sk_lig.smi /home/dkoes/PDBbind/3sk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3so_lig.smi /home/dkoes/PDBbind/3so_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3sr_lig.smi /home/dkoes/PDBbind/3sr_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3t0_lig.smi /home/dkoes/PDBbind/3t0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3td_lig.smi /home/dkoes/PDBbind/3td_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ti_lig.smi /home/dkoes/PDBbind/3ti_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3tp_lig.smi /home/dkoes/PDBbind/3tp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3u2_lig.smi /home/dkoes/PDBbind/3u2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3u4_lig.smi /home/dkoes/PDBbind/3u4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3u4_lig.smi /home/dkoes/PDBbind/3u4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3u6_lig.smi /home/dkoes/PDBbind/3u6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ua_lig.smi /home/dkoes/PDBbind/3ua_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ui_lig.smi /home/dkoes/PDBbind/3ui_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3up_lig.smi /home/dkoes/PDBbind/3up_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3uv_lig.smi /home/dkoes/PDBbind/3uv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3ux_lig.smi /home/dkoes/PDBbind/3ux_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3v3_lig.smi /home/dkoes/PDBbind/3v3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3v3_lig.smi /home/dkoes/PDBbind/3v3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3v4_lig.smi /home/dkoes/PDBbind/3v4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3vj_lig.smi /home/dkoes/PDBbind/3vj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3vj_lig.smi /home/dkoes/PDBbind/3vj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3w6_lig.smi /home/dkoes/PDBbind/3w6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wa_lig.smi /home/dkoes/PDBbind/3wa_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wc_lig.smi /home/dkoes/PDBbind/3wc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wc_lig.smi /home/dkoes/PDBbind/3wc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wc_lig.smi /home/dkoes/PDBbind/3wc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wc_lig.smi /home/dkoes/PDBbind/3wc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wc_lig.smi /home/dkoes/PDBbind/3wc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wc_lig.smi /home/dkoes/PDBbind/3wc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wh_lig.smi /home/dkoes/PDBbind/3wh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wp_lig.smi /home/dkoes/PDBbind/3wp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wp_lig.smi /home/dkoes/PDBbind/3wp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3wu_lig.smi /home/dkoes/PDBbind/3wu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3zh_lig.smi /home/dkoes/PDBbind/3zh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3zj_lig.smi /home/dkoes/PDBbind/3zj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3zj_lig.smi /home/dkoes/PDBbind/3zj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3zj_lig.smi /home/dkoes/PDBbind/3zj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3zk_lig.smi /home/dkoes/PDBbind/3zk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3zp_lig.smi /home/dkoes/PDBbind/3zp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3zq_lig.smi /home/dkoes/PDBbind/3zq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/3zy_lig.smi /home/dkoes/PDBbind/3zy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4a1_lig.smi /home/dkoes/PDBbind/4a1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4a2_lig.smi /home/dkoes/PDBbind/4a2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ac_lig.smi /home/dkoes/PDBbind/4ac_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ao_lig.smi /home/dkoes/PDBbind/4ao_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4az_lig.smi /home/dkoes/PDBbind/4az_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4b6_lig.smi /home/dkoes/PDBbind/4b6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4b8_lig.smi /home/dkoes/PDBbind/4b8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4be_lig.smi /home/dkoes/PDBbind/4be_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4bp_lig.smi /home/dkoes/PDBbind/4bp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4bp_lig.smi /home/dkoes/PDBbind/4bp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4bx_lig.smi /home/dkoes/PDBbind/4bx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4cp_lig.smi /home/dkoes/PDBbind/4cp_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4cy_lig.smi /home/dkoes/PDBbind/4cy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4dc_lig.smi /home/dkoes/PDBbind/4dc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4dc_lig.smi /home/dkoes/PDBbind/4dc_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4dj_lig.smi /home/dkoes/PDBbind/4dj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4dm_lig.smi /home/dkoes/PDBbind/4dm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4do_lig.smi /home/dkoes/PDBbind/4do_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4dt_lig.smi /home/dkoes/PDBbind/4dt_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4e5_lig.smi /home/dkoes/PDBbind/4e5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ej_lig.smi /home/dkoes/PDBbind/4ej_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4er_lig.smi /home/dkoes/PDBbind/4er_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4eu_lig.smi /home/dkoes/PDBbind/4eu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4fe_lig.smi /home/dkoes/PDBbind/4fe_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4fg_lig.smi /home/dkoes/PDBbind/4fg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4fi_lig.smi /home/dkoes/PDBbind/4fi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4fi_lig.smi /home/dkoes/PDBbind/4fi_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ft_lig.smi /home/dkoes/PDBbind/4ft_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4fy_lig.smi /home/dkoes/PDBbind/4fy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4g8_lig.smi /home/dkoes/PDBbind/4g8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ga_lig.smi /home/dkoes/PDBbind/4ga_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ge_lig.smi /home/dkoes/PDBbind/4ge_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4gk_lig.smi /home/dkoes/PDBbind/4gk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4gk_lig.smi /home/dkoes/PDBbind/4gk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4gk_lig.smi /home/dkoes/PDBbind/4gk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4gq_lig.smi /home/dkoes/PDBbind/4gq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4h3_lig.smi /home/dkoes/PDBbind/4h3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4hm_lig.smi /home/dkoes/PDBbind/4hm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4hs_lig.smi /home/dkoes/PDBbind/4hs_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4hw_lig.smi /home/dkoes/PDBbind/4hw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4hx_lig.smi /home/dkoes/PDBbind/4hx_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4hz_lig.smi /home/dkoes/PDBbind/4hz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4i0_lig.smi /home/dkoes/PDBbind/4i0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4i6_lig.smi /home/dkoes/PDBbind/4i6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4i7_lig.smi /home/dkoes/PDBbind/4i7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ie_lig.smi /home/dkoes/PDBbind/4ie_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ie_lig.smi /home/dkoes/PDBbind/4ie_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ii_lig.smi /home/dkoes/PDBbind/4ii_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4is_lig.smi /home/dkoes/PDBbind/4is_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4iu_lig.smi /home/dkoes/PDBbind/4iu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4iu_lig.smi /home/dkoes/PDBbind/4iu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ix_lig.smi /home/dkoes/PDBbind/4ix_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ix_lig.smi /home/dkoes/PDBbind/4ix_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4j2_lig.smi /home/dkoes/PDBbind/4j2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4j2_lig.smi /home/dkoes/PDBbind/4j2_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4j8_lig.smi /home/dkoes/PDBbind/4j8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4jm_lig.smi /home/dkoes/PDBbind/4jm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4k6_lig.smi /home/dkoes/PDBbind/4k6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4k6_lig.smi /home/dkoes/PDBbind/4k6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4k6_lig.smi /home/dkoes/PDBbind/4k6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4k6_lig.smi /home/dkoes/PDBbind/4k6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ka_lig.smi /home/dkoes/PDBbind/4ka_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4kb_lig.smi /home/dkoes/PDBbind/4kb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4kb_lig.smi /home/dkoes/PDBbind/4kb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ki_lig.smi /home/dkoes/PDBbind/4ki_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4l6_lig.smi /home/dkoes/PDBbind/4l6_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4lg_lig.smi /home/dkoes/PDBbind/4lg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ln_lig.smi /home/dkoes/PDBbind/4ln_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4lv_lig.smi /home/dkoes/PDBbind/4lv_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4m7_lig.smi /home/dkoes/PDBbind/4m7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4mm_lig.smi /home/dkoes/PDBbind/4mm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4mn_lig.smi /home/dkoes/PDBbind/4mn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4mn_lig.smi /home/dkoes/PDBbind/4mn_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4mz_lig.smi /home/dkoes/PDBbind/4mz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4mz_lig.smi /home/dkoes/PDBbind/4mz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4mz_lig.smi /home/dkoes/PDBbind/4mz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4n1_lig.smi /home/dkoes/PDBbind/4n1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4nb_lig.smi /home/dkoes/PDBbind/4nb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ng_lig.smi /home/dkoes/PDBbind/4ng_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4nh_lig.smi /home/dkoes/PDBbind/4nh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4nm_lig.smi /home/dkoes/PDBbind/4nm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4no_lig.smi /home/dkoes/PDBbind/4no_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4nu_lig.smi /home/dkoes/PDBbind/4nu_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4o3_lig.smi /home/dkoes/PDBbind/4o3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4o3_lig.smi /home/dkoes/PDBbind/4o3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ob_lig.smi /home/dkoes/PDBbind/4ob_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ob_lig.smi /home/dkoes/PDBbind/4ob_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ob_lig.smi /home/dkoes/PDBbind/4ob_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4of_lig.smi /home/dkoes/PDBbind/4of_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4or_lig.smi /home/dkoes/PDBbind/4or_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4or_lig.smi /home/dkoes/PDBbind/4or_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4or_lig.smi /home/dkoes/PDBbind/4or_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ov_lig.smi /home/dkoes/PDBbind/4ov_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4oy_lig.smi /home/dkoes/PDBbind/4oy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4oy_lig.smi /home/dkoes/PDBbind/4oy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4pz_lig.smi /home/dkoes/PDBbind/4pz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4q3_lig.smi /home/dkoes/PDBbind/4q3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4q3_lig.smi /home/dkoes/PDBbind/4q3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4q3_lig.smi /home/dkoes/PDBbind/4q3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4qb_lig.smi /home/dkoes/PDBbind/4qb_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4qj_lig.smi /home/dkoes/PDBbind/4qj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4qk_lig.smi /home/dkoes/PDBbind/4qk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4qq_lig.smi /home/dkoes/PDBbind/4qq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4qy_lig.smi /home/dkoes/PDBbind/4qy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4r1_lig.smi /home/dkoes/PDBbind/4r1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ri_lig.smi /home/dkoes/PDBbind/4ri_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4rl_lig.smi /home/dkoes/PDBbind/4rl_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4rm_lig.smi /home/dkoes/PDBbind/4rm_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4tz_lig.smi /home/dkoes/PDBbind/4tz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4tz_lig.smi /home/dkoes/PDBbind/4tz_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4u0_lig.smi /home/dkoes/PDBbind/4u0_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4u5_lig.smi /home/dkoes/PDBbind/4u5_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4um_lig.smi /home/dkoes/PDBbind/4um_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4ut_lig.smi /home/dkoes/PDBbind/4ut_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4uw_lig.smi /home/dkoes/PDBbind/4uw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4uw_lig.smi /home/dkoes/PDBbind/4uw_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4wh_lig.smi /home/dkoes/PDBbind/4wh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4wk_lig.smi /home/dkoes/PDBbind/4wk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4wk_lig.smi /home/dkoes/PDBbind/4wk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4wk_lig.smi /home/dkoes/PDBbind/4wk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4wy_lig.smi /home/dkoes/PDBbind/4wy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4x3_lig.smi /home/dkoes/PDBbind/4x3_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4x7_lig.smi /home/dkoes/PDBbind/4x7_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4x9_lig.smi /home/dkoes/PDBbind/4x9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4x9_lig.smi /home/dkoes/PDBbind/4x9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4x9_lig.smi /home/dkoes/PDBbind/4x9_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4xg_lig.smi /home/dkoes/PDBbind/4xg_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4xh_lig.smi /home/dkoes/PDBbind/4xh_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4xk_lig.smi /home/dkoes/PDBbind/4xk_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4xq_lig.smi /home/dkoes/PDBbind/4xq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4xq_lig.smi /home/dkoes/PDBbind/4xq_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4y1_lig.smi /home/dkoes/PDBbind/4y1_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4yy_lig.smi /home/dkoes/PDBbind/4yy_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4z8_lig.smi /home/dkoes/PDBbind/4z8_lig.sdf
babel --gen3D /home/dkoes/PDBbind/4zd_lig.smi /home/dkoes/PDBbind/4zd_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5ae_lig.smi /home/dkoes/PDBbind/5ae_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5af_lig.smi /home/dkoes/PDBbind/5af_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5ag_lig.smi /home/dkoes/PDBbind/5ag_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5ag_lig.smi /home/dkoes/PDBbind/5ag_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5ah_lig.smi /home/dkoes/PDBbind/5ah_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5aj_lig.smi /home/dkoes/PDBbind/5aj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5aj_lig.smi /home/dkoes/PDBbind/5aj_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5dd_lig.smi /home/dkoes/PDBbind/5dd_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5dd_lig.smi /home/dkoes/PDBbind/5dd_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5e4_lig.smi /home/dkoes/PDBbind/5e4_lig.sdf
babel --gen3D /home/dkoes/PDBbind/5ea_lig.smi /home/dkoes/PDBbind/5ea_lig.sdf
